-- ============================================
-- TStudio Sit — Data File
-- Session: Default GTA V Props
-- Generated by the in-resource editor (/sitedit)
-- ============================================

return {
    label = 'Default GTA V Props',

    chairs = {
        {
            model = 'prop_bench_07',
            locations = {
                vector4(-192.9265, -47.7416, 50.2005, 340.03),
                vector4(136.3719, -166.7384, 53.5696, 340.00),
                vector4(126.4833, -162.9818, 53.6495, 340.00),
                vector4(177.3502, -181.1288, 53.1976, 340.00),
                vector4(188.6059, -185.1232, 53.0927, 340.00),
                vector4(201.1994, -189.6311, 52.9791, 340.02),
            },
            seats = {
                {
                    offset = vector3(0.0000, 0.0000, 0.4745),
                    heading = -180.00,
                    anim = { scenario = 'PROP_HUMAN_SEAT_CHAIR' },
                },
                {
                    offset = vector3(0.8071, -0.0473, 0.5363),
                    heading = -180.00,
                    anim = { scenario = 'PROP_HUMAN_SEAT_CHAIR' },
                },
                {
                    offset = vector3(1.9082, -0.0788, 0.6046),
                    heading = -180.00,
                    anim = { scenario = 'PROP_HUMAN_SEAT_CHAIR' },
                },
            },
        },
        {
            model = 'prop_bench_09',
            locations = {
                vector4(164.8296, -898.6967, 29.6563, 249.21),
                vector4(132.6017, -884.2402, 29.6148, 250.00),
                vector4(133.9059, -880.6568, 29.6598, 250.00),
                vector4(151.2137, -934.9046, 29.1050, 249.21),
            },
            seats = {
                {
                    offset = vector3(0.1245, -0.0204, 0.3104),
                    heading = -180.00,
                    anim = { scenario = 'PROP_HUMAN_SEAT_BENCH' },
                },
            },
        },
        {
            model = 'prop_bench_08',
            locations = {
                vector4(1075.0895, -735.9675, 55.7436, 140.38),
            },
            seats = {
                {
                    offset = vector3(0.7692, 0.1297, 0.4915),
                    heading = 180.00,
                    anim = { scenario = 'PROP_HUMAN_SEAT_CHAIR_UPRIGHT' },
                },
                {
                    offset = vector3(-0.6773, 0.0235, 0.4915),
                    heading = 180.00,
                    anim = { scenario = 'PROP_HUMAN_SEAT_CHAIR_UPRIGHT' },
                },
            },
        },
        {
            model = 'prop_chair_01a',
            locations = {
                vector4(122.7986, -864.0151, 30.1267, 276.18),
                vector4(124.8539, -864.9058, 30.1267, 58.22),
                vector4(125.8386, -874.0459, 30.1267, 163.01),
                vector4(126.9794, -872.6453, 30.1267, 306.16),
                vector4(126.9258, -866.9358, 30.1267, 326.49),
                vector4(121.1189, -864.1760, 30.1267, 90.59),
                vector4(126.1824, -869.9907, 30.1267, 342.28),
                vector4(126.0865, -871.7946, 30.1267, 199.13),
                vector4(126.5291, -865.7932, 30.1267, 232.63),
                vector4(126.3425, -868.6455, 30.1267, 183.34),
            },
            seats = {
                {
                    offset = vector3(0.0000, 0.0000, 0.4888),
                    heading = -180.00,
                    anim = { scenario = 'PROP_HUMAN_SEAT_CHAIR' },
                },
            },
        },
    },
}
