const fs = require('fs');

const en = {
    'could_not_get_tug_boat': "Could not get tug boat",
    'you_already_have_an_active_or': "You already have an active or starting mission.",
    'could_not_get_squad_tug_boat': "Could not get squad tug boat",
    'container_could_not_be_secured': "Container could not be secured to the tug.",
    'container_could_not_be_picked': "Container could not be picked up.",
    'e_complete_delivery': "[E] - Complete delivery",
    'move_to_the_tug_to_complete_de': "Move to the tug to complete delivery",
    'e_unload_all_containers_to_rig': "[E] - Unload all containers to rig",
    'e_attach_container_to_tug': "[E] - Attach container to tug",
    'e_detach_container_drive_to_tu': "[E] - Detach container   ·   Drive to tug to load",
    'e_pick_up_container_forklift': "[E] - Pick up container (forklift)",
    'squad_boat_ready_you_have_keys': "Squad boat ready - you have keys and fuel",
    'container_secured_to_tug': "Container secured to tug.",
    'invalid_ped_model_for_outfit': "Invalid ped model for outfit",
    'outfit_applied': "Outfit applied",
    'you_died_mission_cancelled': "You died. Mission cancelled.",
    'filling_started_wait_1_minute': "Filling started. Wait 1 minute.",
    'you_must_drill_and_fill_the_ba': "You must drill and fill the barrel first!",
    'barrel_is_filling_please_wait': "Barrel is filling! Please wait.",
    'open_the_containers_before_loa': "Open the containers before loading barrels.",
    'container_is_full_max_6_barrel': "Container is full (max 6 barrels).",
    'already_open': "Already open",
    'container_opened': "Container opened",
    'container_lock_not_cleared': "Container lock not cleared.",
    'container_closed': "Container closed",
    'e_put_barrel_in_container': "[E] - Put barrel in container",
    'start_filling': "Start Filling",
    'pick_up_barrel': "Pick up barrel",
    'put_barrel_in_container': "Put barrel in container",
    'open_container': "Open Container",
    'close_container': "Close Container",
    'closing_the_container': "Closing the container...",
    'oil_rig_job': "Oil Rig Job",
    'talk': "Talk",
    'press_input_detonate_to_pick_u': "Press ~INPUT_DETONATE~ to pick up this container up",
    'press_input_detonate_to_detach': "Press ~INPUT_DETONATE~ to detach this container",
    'mission_failed_the_helicopter': "Mission Failed! The helicopter went too far from the mission area.",
    'warning_return_to_the_mission': "WARNING: Return to the mission area immediately or the mission will fail!",
    'could_not_get_helicopter': "Could not get helicopter",
    'e_return_skylift': "[E] - Return Skylift",
    'driver_can_return_skylift_e': "Driver can return Skylift [E]",
    'container_picked_up_fly_to_the': "Container picked up. Fly to the Oil Rig.",
    'container_automatically_attach': "Container automatically attached! Take it to the dropoff point.",
    'container_delivered_return_the': "Container delivered! Return the Skylift.",
    'squad_heli_ready_you_are_passe': "Squad heli ready - you are passenger. Driver flies and picks up containers.",
    'oil_rig_2': "Oil Rig 2",
    'oil_rig_3': "Oil Rig 3",
    'oil_rig_4': "Oil Rig 4",
    'oil_rig_5': "Oil Rig 5",
    'oil_rig_6': "Oil Rig 6",
    'oil_rig_7': "Oil Rig 7",
    'oil_rig_8': "Oil Rig 8",
    'oil_rig_9': "Oil Rig 9",
    'oil_rig_10': "Oil Rig 10"
};

const de = {
    'could_not_get_tug_boat': "Schlepper konnte nicht geholt werden",
    'you_already_have_an_active_or': "Sie haben bereits eine aktive oder startende Mission.",
    'could_not_get_squad_tug_boat': "Trupp-Schlepper konnte nicht geholt werden",
    'container_could_not_be_secured': "Container konnte nicht am Schlepper gesichert werden.",
    'container_could_not_be_picked': "Container konnte nicht aufgenommen werden.",
    'e_complete_delivery': "[E] - Lieferung abschliessen",
    'move_to_the_tug_to_complete_de': "Gehen Sie zum Schlepper, um die Lieferung abzuschliessen",
    'e_unload_all_containers_to_rig': "[E] - Alle Container auf die Bohrinsel entladen",
    'e_attach_container_to_tug': "[E] - Container am Schlepper befestigen",
    'e_detach_container_drive_to_tu': "[E] - Container abkoppeln   ·   Zum Schlepper fahren",
    'e_pick_up_container_forklift': "[E] - Container aufnehmen (Gabelstapler)",
    'squad_boat_ready_you_have_keys': "Trupp-Boot bereit - Sie haben Schluessel und Treibstoff",
    'container_secured_to_tug': "Container am Schlepper gesichert.",
    'invalid_ped_model_for_outfit': "Ungueltiges Modell fuer das Outfit",
    'outfit_applied': "Outfit angewendet",
    'you_died_mission_cancelled': "Sie sind gestorben. Mission abgebrochen.",
    'filling_started_wait_1_minute': "Befuellung gestartet. 1 Minute warten.",
    'you_must_drill_and_fill_the_ba': "Sie muessen das Fass zuerst anbohren und befuellen!",
    'barrel_is_filling_please_wait': "Fass wird gefuellt! Bitte warten.",
    'open_the_containers_before_loa': "Oeffnen Sie die Container, bevor Sie die Faesser laden.",
    'container_is_full_max_6_barrel': "Container ist voll (max. 6 Faesser).",
    'already_open': "Bereits geoeffnet",
    'container_opened': "Container geoeffnet",
    'container_lock_not_cleared': "Container-Schloss nicht entfernt.",
    'container_closed': "Container geschlossen",
    'e_put_barrel_in_container': "[E] - Fass in Container stellen",
    'start_filling': "Befuellung starten",
    'pick_up_barrel': "Fass aufnehmen",
    'put_barrel_in_container': "Fass in Container stellen",
    'open_container': "Container oeffnen",
    'close_container': "Container schliessen",
    'closing_the_container': "Container wird geschlossen...",
    'oil_rig_job': "Bohrinsel-Job",
    'talk': "Sprechen",
    'press_input_detonate_to_pick_u': "Druecken Sie ~INPUT_DETONATE~, um diesen Container aufzunehmen",
    'press_input_detonate_to_detach': "Druecken Sie ~INPUT_DETONATE~, um diesen Container abzukoppeln",
    'mission_failed_the_helicopter': "Mission fehlgeschlagen! Der Hubschrauber hat sich zu weit entfernt.",
    'warning_return_to_the_mission': "WARNUNG: Kehren Sie sofort zum Missionsgebiet zurueck!",
    'could_not_get_helicopter': "Hubschrauber konnte nicht geholt werden",
    'e_return_skylift': "[E] - Skylift zurueckgeben",
    'driver_can_return_skylift_e': "Fahrer kann Skylift zurueckgeben [E]",
    'container_picked_up_fly_to_the': "Container aufgenommen. Fliegen Sie zur Bohrinsel.",
    'container_automatically_attach': "Container automatisch befestigt! Bringen Sie ihn zum Abgabeort.",
    'container_delivered_return_the': "Container abgeliefert! Geben Sie den Skylift zurueck.",
    'squad_heli_ready_you_are_passe': "Trupp-Heli bereit - Sie sind Beifahrer.",
    'oil_rig_2': "Bohrinsel 2",
    'oil_rig_3': "Bohrinsel 3",
    'oil_rig_4': "Bohrinsel 4",
    'oil_rig_5': "Bohrinsel 5",
    'oil_rig_6': "Bohrinsel 6",
    'oil_rig_7': "Bohrinsel 7",
    'oil_rig_8': "Bohrinsel 8",
    'oil_rig_9': "Bohrinsel 9",
    'oil_rig_10': "Bohrinsel 10"
};

const es = {
    'could_not_get_tug_boat': "No se pudo obtener el remolcador",
    'you_already_have_an_active_or': "Ya tienes una mision activa o en inicio.",
    'could_not_get_squad_tug_boat': "No se pudo obtener el remolcador del escuadron",
    'container_could_not_be_secured': "El contenedor no pudo asegurarse al remolcador.",
    'container_could_not_be_picked': "El contenedor no pudo ser recogido.",
    'e_complete_delivery': "[E] - Completar entrega",
    'move_to_the_tug_to_complete_de': "Muevete al remolcador para completar la entrega",
    'e_unload_all_containers_to_rig': "[E] - Descargar todos los contenedores en la plataforma",
    'e_attach_container_to_tug': "[E] - Asegurar contenedor al remolcador",
    'e_detach_container_drive_to_tu': "[E] - Soltar contenedor   ·   Conducir para cargar",
    'e_pick_up_container_forklift': "[E] - Recoger contenedor (montacargas)",
    'squad_boat_ready_you_have_keys': "Barco listo - tienes llaves y combustible",
    'container_secured_to_tug': "Contenedor asegurado al remolcador.",
    'invalid_ped_model_for_outfit': "Modelo invalido para el traje",
    'outfit_applied': "Traje aplicado",
    'you_died_mission_cancelled': "Has muerto. Mision cancelada.",
    'filling_started_wait_1_minute': "Llenado iniciado. Espera 1 minuto.",
    'you_must_drill_and_fill_the_ba': "Debes perforar y llenar el barril primero!",
    'barrel_is_filling_please_wait': "El barril se esta llenando! Por favor espera.",
    'open_the_containers_before_loa': "Abre los contenedores antes de cargar los barriles.",
    'container_is_full_max_6_barrel': "El contenedor esta lleno (max. 6 barriles).",
    'already_open': "Ya esta abierto",
    'container_opened': "Contenedor abierto",
    'container_lock_not_cleared': "El candado no fue retirado.",
    'container_closed': "Contenedor cerrado",
    'e_put_barrel_in_container': "[E] - Poner barril en contenedor",
    'start_filling': "Iniciar llenado",
    'pick_up_barrel': "Recoger barril",
    'put_barrel_in_container': "Poner barril en contenedor",
    'open_container': "Abrir contenedor",
    'close_container': "Cerrar contenedor",
    'closing_the_container': "Cerrando el contenedor...",
    'oil_rig_job': "Trabajo Petrolero",
    'talk': "Hablar",
    'press_input_detonate_to_pick_u': "Presiona ~INPUT_DETONATE~ para recoger el contenedor",
    'press_input_detonate_to_detach': "Presiona ~INPUT_DETONATE~ para soltar el contenedor",
    'mission_failed_the_helicopter': "Mision fallida! El helicoptero se alejo demasiado.",
    'warning_return_to_the_mission': "ADVERTENCIA: Regresa a la zona de la mision de inmediato!",
    'could_not_get_helicopter': "No se pudo obtener el helicoptero",
    'e_return_skylift': "[E] - Devolver Skylift",
    'driver_can_return_skylift_e': "El piloto puede devolver el Skylift [E]",
    'container_picked_up_fly_to_the': "Contenedor recogido. Vuela a la plataforma.",
    'container_automatically_attach': "Contenedor asegurado automaticamente! Llevalo a la entrega.",
    'container_delivered_return_the': "Contenedor entregado! Devuelve el Skylift.",
    'squad_heli_ready_you_are_passe': "Heli de escuadron listo - eres pasajero.",
    'oil_rig_2': "Plataforma 2",
    'oil_rig_3': "Plataforma 3",
    'oil_rig_4': "Plataforma 4",
    'oil_rig_5': "Plataforma 5",
    'oil_rig_6': "Plataforma 6",
    'oil_rig_7': "Plataforma 7",
    'oil_rig_8': "Plataforma 8",
    'oil_rig_9': "Plataforma 9",
    'oil_rig_10': "Plataforma 10"
};

const fr = {
    'could_not_get_tug_boat': "Impossible d'obtenir le remorqueur",
    'you_already_have_an_active_or': "Vous avez deja une mission active ou en cours.",
    'could_not_get_squad_tug_boat': "Impossible d'obtenir le remorqueur de l'equipe",
    'container_could_not_be_secured': "Le conteneur n'a pas pu etre fixe au remorqueur.",
    'container_could_not_be_picked': "Le conteneur n'a pas pu etre ramasse.",
    'e_complete_delivery': "[E] - Terminer la livraison",
    'move_to_the_tug_to_complete_de': "Allez au remorqueur pour terminer la livraison",
    'e_unload_all_containers_to_rig': "[E] - Decharger tous les conteneurs sur la plateforme",
    'e_attach_container_to_tug': "[E] - Attacher le conteneur au remorqueur",
    'e_detach_container_drive_to_tu': "[E] - Detacher le conteneur   ·   Conduire pour charger",
    'e_pick_up_container_forklift': "[E] - Ramasser le conteneur (chariot elevateur)",
    'squad_boat_ready_you_have_keys': "Bateau pret - vous avez les cles et le carburant",
    'container_secured_to_tug': "Conteneur attache au remorqueur.",
    'invalid_ped_model_for_outfit': "Modele invalide pour la tenue",
    'outfit_applied': "Tenue appliquee",
    'you_died_mission_cancelled': "Vous etes mort. Mission annulee.",
    'filling_started_wait_1_minute': "Remplissage commence. Attendez 1 minute.",
    'you_must_drill_and_fill_the_ba': "Vous devez d'abord percer et remplir le baril !",
    'barrel_is_filling_please_wait': "Le baril se remplit ! Veuillez patienter.",
    'open_the_containers_before_loa': "Ouvrez les conteneurs avant de charger les barils.",
    'container_is_full_max_6_barrel': "Le conteneur est plein (max. 6 barils).",
    'already_open': "Deja ouvert",
    'container_opened': "Conteneur ouvert",
    'container_lock_not_cleared': "Le verrou du conteneur n'est pas retire.",
    'container_closed': "Conteneur ferme",
    'e_put_barrel_in_container': "[E] - Mettre le baril dans le conteneur",
    'start_filling': "Commencer le remplissage",
    'pick_up_barrel': "Ramasser le baril",
    'put_barrel_in_container': "Mettre le baril dans le conteneur",
    'open_container': "Ouvrir le conteneur",
    'close_container': "Fermer le conteneur",
    'closing_the_container': "Fermeture du conteneur...",
    'oil_rig_job': "Travail petrolier",
    'talk': "Parler",
    'press_input_detonate_to_pick_u': "Appuyez sur ~INPUT_DETONATE~ pour ramasser le conteneur",
    'press_input_detonate_to_detach': "Appuyez sur ~INPUT_DETONATE~ pour detacher le conteneur",
    'mission_failed_the_helicopter': "Mission echouee ! L'helicoptere s'est trop eloigne.",
    'warning_return_to_the_mission': "ATTENTION : Retournez immediatement dans la zone de mission !",
    'could_not_get_helicopter': "Impossible d'obtenir l'helicoptere",
    'e_return_skylift': "[E] - Retourner le Skylift",
    'driver_can_return_skylift_e': "Le pilote peut retourner le Skylift [E]",
    'container_picked_up_fly_to_the': "Conteneur ramasse. Volez vers la plateforme.",
    'container_automatically_attach': "Conteneur attache automatiquement ! Apportez-le a la livraison.",
    'container_delivered_return_the': "Conteneur livre ! Retournez le Skylift.",
    'squad_heli_ready_you_are_passe': "Helico pret - vous etes passager.",
    'oil_rig_2': "Plateforme 2",
    'oil_rig_3': "Plateforme 3",
    'oil_rig_4': "Plateforme 4",
    'oil_rig_5': "Plateforme 5",
    'oil_rig_6': "Plateforme 6",
    'oil_rig_7': "Plateforme 7",
    'oil_rig_8': "Plateforme 8",
    'oil_rig_9': "Plateforme 9",
    'oil_rig_10': "Plateforme 10"
};

const pt = {
    'could_not_get_tug_boat': "Nao foi possivel obter o rebocador",
    'you_already_have_an_active_or': "Voce ja tem uma missao ativa ou a iniciar.",
    'could_not_get_squad_tug_boat': "Nao foi possivel obter o rebocador do esquadrao",
    'container_could_not_be_secured': "O conteiner nao pode ser fixado ao rebocador.",
    'container_could_not_be_picked': "O conteiner nao pode ser recolhido.",
    'e_complete_delivery': "[E] - Completar entrega",
    'move_to_the_tug_to_complete_de': "Va ao rebocador para completar a entrega",
    'e_unload_all_containers_to_rig': "[E] - Descarregar todos os conteineres na plataforma",
    'e_attach_container_to_tug': "[E] - Fixar conteiner ao rebocador",
    'e_detach_container_drive_to_tu': "[E] - Soltar conteiner   ·   Dirija para carregar",
    'e_pick_up_container_forklift': "[E] - Pegar conteiner (empilhadeira)",
    'squad_boat_ready_you_have_keys': "Barco de esquadrao pronto - tem chaves e combustivel",
    'container_secured_to_tug': "Conteiner fixado ao rebocador.",
    'invalid_ped_model_for_outfit': "Modelo invalido para a roupa",
    'outfit_applied': "Roupa aplicada",
    'you_died_mission_cancelled': "Voce morreu. Missao cancelada.",
    'filling_started_wait_1_minute': "Enchimento iniciado. Aguarde 1 minuto.",
    'you_must_drill_and_fill_the_ba': "Voce deve perfurar e encher o barril primeiro!",
    'barrel_is_filling_please_wait': "O barril esta a encher! Por favor, aguarde.",
    'open_the_containers_before_loa': "Abra os conteineres antes de carregar os barris.",
    'container_is_full_max_6_barrel': "O conteiner esta cheio (max. 6 barris).",
    'already_open': "Ja esta aberto",
    'container_opened': "Conteiner aberto",
    'container_lock_not_cleared': "A fechadura do conteiner nao foi removida.",
    'container_closed': "Conteiner fechado",
    'e_put_barrel_in_container': "[E] - Colocar barril no conteiner",
    'start_filling': "Iniciar enchimento",
    'pick_up_barrel': "Pegar barril",
    'put_barrel_in_container': "Colocar barril no conteiner",
    'open_container': "Abrir conteiner",
    'close_container': "Fechar conteiner",
    'closing_the_container': "A fechar o conteiner...",
    'oil_rig_job': "Trabalho Petrolifero",
    'talk': "Falar",
    'press_input_detonate_to_pick_u': "Pressione ~INPUT_DETONATE~ para pegar o conteiner",
    'press_input_detonate_to_detach': "Pressione ~INPUT_DETONATE~ para soltar o conteiner",
    'mission_failed_the_helicopter': "Missao falhou! O helicoptero foi para muito longe.",
    'warning_return_to_the_mission': "AVISO: Volte imediatamente para a area da missao!",
    'could_not_get_helicopter': "Nao foi possivel obter o helicoptero",
    'e_return_skylift': "[E] - Devolver Skylift",
    'driver_can_return_skylift_e': "O piloto pode devolver o Skylift [E]",
    'container_picked_up_fly_to_the': "Conteiner recolhido. Voe para a plataforma.",
    'container_automatically_attach': "Conteiner fixado automaticamente! Leve-o para entrega.",
    'container_delivered_return_the': "Conteiner entregue! Devolva o Skylift.",
    'squad_heli_ready_you_are_passe': "Heli de esquadrao pronto - e passageiro.",
    'oil_rig_2': "Plataforma 2",
    'oil_rig_3': "Plataforma 3",
    'oil_rig_4': "Plataforma 4",
    'oil_rig_5': "Plataforma 5",
    'oil_rig_6': "Plataforma 6",
    'oil_rig_7': "Plataforma 7",
    'oil_rig_8': "Plataforma 8",
    'oil_rig_9': "Plataforma 9",
    'oil_rig_10': "Plataforma 10"
};

const pl = {
    'could_not_get_tug_boat': "Nie mozna uzyskac holownika",
    'you_already_have_an_active_or': "Masz juz aktywna lub rozpoczynajaca sie misje.",
    'could_not_get_squad_tug_boat': "Nie mozna uzyskac holownika zespolu",
    'container_could_not_be_secured': "Nie mozna zabezpieczyc kontenera na holowniku.",
    'container_could_not_be_picked': "Nie mozna podniesc kontenera.",
    'e_complete_delivery': "[E] - Zakoncz dostawe",
    'move_to_the_tug_to_complete_de': "Podejdz do holownika, aby zakonczyc dostawe",
    'e_unload_all_containers_to_rig': "[E] - Rozladuj wszystkie kontenery na platforme",
    'e_attach_container_to_tug': "[E] - Przymocuj kontener do holownika",
    'e_detach_container_drive_to_tu': "[E] - Odlacz kontener   ·   Jedz aby zaladowac",
    'e_pick_up_container_forklift': "[E] - Podnies kontener (wozek)",
    'squad_boat_ready_you_have_keys': "Lodz zespolowa gotowa - masz klucze i paliwo",
    'container_secured_to_tug': "Kontener zabezpieczony na holowniku.",
    'invalid_ped_model_for_outfit': "Nieprawidlowy model dla stroju",
    'outfit_applied': "Stroj zastosowany",
    'you_died_mission_cancelled': "Zginales. Misja anulowana.",
    'filling_started_wait_1_minute': "Napelnianie rozpoczeli sie. Poczekaj 1 minute.",
    'you_must_drill_and_fill_the_ba': "Najpierw musisz wywiercic i napelnic beczke!",
    'barrel_is_filling_please_wait': "Beczka sie napelnia! Prosze czekac.",
    'open_the_containers_before_loa': "Otworz kontenery przed zaladowaniem beczek.",
    'container_is_full_max_6_barrel': "Kontener jest pelny (maks. 6 beczek).",
    'already_open': "Juz otwarte",
    'container_opened': "Kontener otwarty",
    'container_lock_not_cleared': "Zamek kontenera nie zostal usuniety.",
    'container_closed': "Kontener zamkniety",
    'e_put_barrel_in_container': "[E] - Wloz beczke do kontenera",
    'start_filling': "Zacznij napelniac",
    'pick_up_barrel': "Podnies beczke",
    'put_barrel_in_container': "Wloz beczke do kontenera",
    'open_container': "Otworz kontener",
    'close_container': "Zamknij kontener",
    'closing_the_container': "Zamykanie kontenera...",
    'oil_rig_job': "Praca na platformie wiertniczej",
    'talk': "Rozmawiaj",
    'press_input_detonate_to_pick_u': "Nacisnij ~INPUT_DETONATE~, aby podniesc kontener",
    'press_input_detonate_to_detach': "Nacisnij ~INPUT_DETONATE~, aby odlaczyc kontener",
    'mission_failed_the_helicopter': "Misja nieudana! Helikopter odlecial za daleko.",
    'warning_return_to_the_mission': "OSTRZEZENIE: Wroc natychmiast na obszar misji!",
    'could_not_get_helicopter': "Nie mozna uzyskac helikoptera",
    'e_return_skylift': "[E] - Zwroc Skylift",
    'driver_can_return_skylift_e': "Kierowca moze zwrocic Skylift [E]",
    'container_picked_up_fly_to_the': "Kontener podniesiony. Lec na platforme.",
    'container_automatically_attach': "Kontener automatycznie przymocowany! Zabierz go do celu.",
    'container_delivered_return_the': "Kontener dostarczony! Zwroc Skylift.",
    'squad_heli_ready_you_are_passe': "Heli zespolowy gotowy - jestes pasazerem.",
    'oil_rig_2': "Platforma 2",
    'oil_rig_3': "Platforma 3",
    'oil_rig_4': "Platforma 4",
    'oil_rig_5': "Platforma 5",
    'oil_rig_6': "Platforma 6",
    'oil_rig_7': "Platforma 7",
    'oil_rig_8': "Platforma 8",
    'oil_rig_9': "Platforma 9",
    'oil_rig_10': "Platforma 10"
};

function generateBlock(dict, langCode) {
    let block = `    ['${langCode}'] = {\n`;
    for (let key in dict) {
        block += `        ['${key}'] = '${dict[key].replace(/'/g, "\\'")}',\n`;
    }
    block += `    },\n`;
    return block;
}

let luaContent = `local Locale = {}

Locale.Locale =  'en'   -- en, de, es, fr, pt, pl

local Translations = {
${generateBlock(en, 'en')}${generateBlock(de, 'de')}${generateBlock(es, 'es')}${generateBlock(fr, 'fr')}${generateBlock(pt, 'pt')}${generateBlock(pl, 'pl')}}

function locale(key, ...)
    local lang = Translations[Locale.Locale] or Translations['en']
    local translation = lang[key] or Translations['en'][key] or key
    
    if ... then
        return string.format(translation, ...)
    end
    
    return translation
end

_G.locale = locale

return Locale
`;

fs.writeFileSync('locales/locale.lua', luaContent, 'utf8');
console.log('locales/locale.lua updated successfully.');
